# Generated by Django 5.2.6 on 2026-06-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_customuser_middle_initial_customuser_suffix_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='spouse_name',
        ),
        migrations.AddField(
            model_name='case',
            name='spouse_first_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='spouse_last_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='spouse_middle_initial',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='spouse_suffix',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
