# Generated by Django 5.2.6 on 2026-06-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_remove_case_spouse_name_case_spouse_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='co_owners_details',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
