# Generated by Django 5.2.6 on 2026-06-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_case_co_owners_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='lot_number',
            field=models.CharField(default='NA', help_text='Permanent cadastral map identifier (e.g. Lot 123-B)', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='previous_tax_dec_number',
            field=models.CharField(default='NA', help_text='Previous Tax Dec Number (e.g. TD-2023-001, NA, New)', max_length=50),
            preserve_default=False,
        ),
    ]
