# Generated by Django 5.2.6 on 2026-06-26 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_case_lot_number_case_previous_tax_dec_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='numberer_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='numberer_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='numbered_cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
