# Generated by Django 5.2.6 on 2026-07-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_case_numberer_assigned_at_case_numberer_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='original_area',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='transferred_area',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(blank=True, choices=[('land_first_time', 'Land declared for the first-time'), ('building_improvements', 'Building and other improvements / Machineries'), ('subdivision_consolidation', 'Subdivision or Consolidation'), ('reassessment_reclassification', 'Re-assessment / Re-classification'), ('area_increase_decrease', 'Increase / Decrease of Area'), ('transfer_ownership_tax_decl', 'Transfer of Ownership of Tax Declaration'), ('transfer_ownership_partial_segregation', 'Transfer of Ownership (Partial / Segregation)')], default='', max_length=64),
        ),
    ]
