# Generated by Django 5.2.6 on 2026-07-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_case_original_area_case_transferred_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('not_received', 'Not Received'), ('received', 'Received'), ('to_examine', 'To Examine'), ('in_review', 'Under Examination'), ('for_taxmapping', 'For Taxmapping'), ('for_approval', 'For Approval'), ('approved', 'Approved'), ('for_numbering', 'For Numbering'), ('for_release', 'For Release'), ('released', 'Released'), ('client_correction', 'Client Correction (30 days)'), ('returned', 'Returned (Legacy)'), ('withdrawn', 'Withdrawn'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('active', 'Active')], default='not_received', max_length=20),
        ),
    ]
