# Generated by Django 5.2.6 on 2026-07-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_legacy_override',
            field=models.BooleanField(default=False, help_text='Bypass Mother Lot checks for pre-2000s records'),
        ),
        migrations.AlterField(
            model_name='case',
            name='previous_tax_dec_number',
            field=models.CharField(blank=True, help_text='Previous Tax Dec Number (e.g. TD-2023-001, NA, New)', max_length=50, null=True),
        ),
    ]
