# Generated by Django 5.2.6 on 2026-07-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_case_is_legacy_override_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(blank=True, choices=[('land_first_time', 'Land declared for the first-time'), ('building_improvements', 'Building and other improvements / Machineries'), ('subdivision_consolidation', 'Subdivision or Consolidation'), ('reassessment_reclassification', 'Re-assessment / Re-classification'), ('area_increase_decrease', 'Increase / Decrease of Area'), ('transfer_ownership_tax_decl', 'Transfer of Ownership of Tax Declaration'), ('transfer_ownership_partial_segregation', 'Transfer of Ownership (Partial / Segregation)'), ('retained_area_new_mother_lot', 'Retained Area (New Mother Lot)')], default='', max_length=64),
        ),
    ]
