# Generated by Django 5.2.6 on 2026-07-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_alter_case_case_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='for_approval_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
