# Generated by Django 5.2.6 on 2026-07-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_case_for_approval_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
