# Generated by Django 5.2.6 on 2026-07-27 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_case_approved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_docs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='replacement_reason',
            field=models.TextField(blank=True, help_text='Examiner remark at time of replacement', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('login_failed', 'User Login Failed'), ('logout', 'User Logout'), ('create_user', 'Create User Account'), ('update_user', 'Update User Account'), ('deactivate_user', 'Deactivate User'), ('reactivate_user', 'Reactivate User'), ('reset_password', 'Reset Password'), ('activation_email_sent', 'Activation Email Sent'), ('activate_account', 'Account Activated'), ('password_reset_request', 'Password Reset Requested'), ('password_reset_complete', 'Password Reset Completed'), ('case_create', 'Transaction Created'), ('case_update', 'Transaction Updated'), ('case_document_review', 'Transaction Document Reviewed'), ('case_remark', 'Transaction Remark Added'), ('case_status_change', 'Transaction Status Changed'), ('case_receipt', 'Transaction Physically Received'), ('case_assignment', 'Transaction Assigned'), ('case_approval', 'Transaction Approved'), ('case_rejection', 'Transaction Rejected'), ('case_numbered', 'Transaction Number Assigned'), ('case_release', 'Transaction Released'), ('case_email_update', 'Sent Email Update'), ('support_feedback', 'Support Feedback Submitted')], max_length=50),
        ),
    ]
